### PR TITLE
fix: thailand/SEA 144P unable to load

### PR DESCRIPTION
**Pull request by JasonKhew96**
地球人刚发明网络

### CODE REVIEW

**Comment by ipcjs** [comment]
🤣

**Comment by JasonKhew96** [comment]
CI 炸了

**Comment by ipcjs** [comment]
🤔这是什么鬼错误

**Comment by JasonKhew96** [comment]
重新跑一下试试？

**Comment by ipcjs** [comment]
开了缓存就不灵了，艹🥲
https://github.com/ipcjs/bilibili-helper/runs/7160590827?check_suite_focus=true

**Comment by ipcjs** [comment]
手动清了下编译缓存，终于好了😅
https://docs.github.com/en/rest/actions/cache#delete-github-actions-caches-for-a-repository-using-a-cache-key

**Pull request merged**
